-- Align monitoring-related schema with mobile/web expectations.

-- Storage logs (daily device storage stats)
CREATE TABLE IF NOT EXISTS public.storage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code TEXT NOT NULL,
    device_id TEXT NOT NULL,
    log_date DATE NOT NULL,
    total_bytes BIGINT NOT NULL,
    used_bytes BIGINT NOT NULL,
    free_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_storage_logs_unique
ON public.storage_logs(employee_code, device_id, log_date);

CREATE INDEX IF NOT EXISTS idx_storage_logs_employee
ON public.storage_logs(employee_code);

CREATE INDEX IF NOT EXISTS idx_storage_logs_device
ON public.storage_logs(device_id);

CREATE INDEX IF NOT EXISTS idx_storage_logs_date
ON public.storage_logs(log_date);

ALTER TABLE public.storage_logs ENABLE ROW LEVEL SECURITY;

-- Network logs: add per-transport byte counters if missing
ALTER TABLE public.network_logs
    ADD COLUMN IF NOT EXISTS wifi_rx_bytes BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS wifi_tx_bytes BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mobile_rx_bytes BIGINT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mobile_tx_bytes BIGINT DEFAULT 0;

-- Call recordings: ensure table + columns for web/mobile fields
CREATE TABLE IF NOT EXISTS public.call_recordings (
    id TEXT PRIMARY KEY,
    user_id UUID DEFAULT auth.uid(),
    phone_number TEXT NOT NULL,
    contact_name TEXT,
    direction TEXT,
    call_type TEXT,
    scheduled_time TIMESTAMPTZ,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    duration_seconds INTEGER DEFAULT 0,
    file_url TEXT,
    upload_status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_accuracy DOUBLE PRECISION,
    location_timestamp TIMESTAMPTZ
);

ALTER TABLE public.call_recordings
    ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid(),
    ADD COLUMN IF NOT EXISTS call_type TEXT,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS location_accuracy DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS location_timestamp TIMESTAMPTZ;

ALTER TABLE public.call_recordings
    ALTER COLUMN user_id SET DEFAULT auth.uid();

ALTER TABLE public.call_recordings ENABLE ROW LEVEL SECURITY;

-- Device health logs: align expected columns if missing
ALTER TABLE public.device_health_logs
    ADD COLUMN IF NOT EXISTS check_timestamp TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
